# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZ4oV48S8R84Ak-LSn9enPXz8sM0bPAt
"""

import requests
url = 'http://localhost:5000/predict_api'
r = requests.post(url, json={'Open':2168, 'High':2183, 'Low':10000})

print(r.json())